---
- name: Instalar Node Exporter
  hosts: servidores
  become: true
  become_user: root

  tasks:
  - name: Criar grupo node_exporter
    ansible.builtin.group:
      name: nodeexporter
      state: present
      system: true

  - name: Criar usuario node_exporter
    ansible.builtin.user:
      name: nodeexporter
      shell: /bin/nologin
      system: true
      group: nodeexporter

  - name: download node exporter
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
      dest: /tmp

  - name: Unzip node exporter
    unarchive:
      remote_src: yes
      src: /tmp/node_exporter-1.5.0.linux-amd64.tar.gz
      dest: /tmp

  - name: mover node exporter para /usr/local/bin
    copy:
      src: /tmp/node_exporter-1.5.0.linux-amd64/node_exporter
      dest: /usr/local/bin/node_exporter
      remote_src: yes
      owner: nodeexporter
      group: nodeexporter
      mode: 0755

  - name: instale o arquivo unit no systemd
    template:
      src: service_systemd/node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
      owner: nodeexporter
      group: nodeexporter
      mode: 0600

  - name: configurar o systemd para usar o servi√ßo
    systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: node_exporter.service
